name: fourth-step-action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          make install
          make lint
          make test
      - name: coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.LOKOT_SECRET }}
        with:
          coverageCommand: make coverage
          debug: true